### PR TITLE
Replace unsupported unbounded joint

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
@olivier-stasse can you give me write access to this repo ?

**Comment by olivier-stasse** [comment]
@jmirabel Done

**Comment by olivier-stasse** [comment]
Would not be better to modify the cpp code not able to handle inf ???

**Comment by jmirabel** [comment]
The error comes from urdfdom. I could propose them a patch but that's going to take a *loooong* time before it reaches us.

**Comment by jmirabel** [comment]
I think the problem is only on 18.04 and not on 16.04.

**Comment by olivier-stasse** [comment]
Ok sorry I did not catch it was coming from urdfdom.

**Pull request merged**
